server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-add-partitions: true
      group-id: book-management-service-group
      auto-offset-reset: earliest
    producer:
      auto-add-partitions: true
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false

  datasource:
    url: jdbc:postgresql://localhost:15432/library
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db.migration